[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }

[[language]]
name = "svelte"
auto-format = true
formatter = { command = 'npx', args = ["prettier", "--parser", "svelte"] }

[[language]]
name = "vue"
auto-format = true
formatter = { command = 'npx', args = ["prettier", "--parser", "vue"] }

[[language]]
name = "python"
auto-format = true

[language.formatter]
command = "black"
args = ["--line-length", "120", "--skip-string-normalization", "--quiet", "-"]
