[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }

[[language]]
name = "svelte"
auto-format = true
formatter = { command = 'npx', args = ["prettier", "--parser", "svelte"] }

[[language]]
name = "vue"
auto-format = true
formatter = { command = 'npx', args = ["prettier", "--parser", "vue"] }

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "typst"
file-types = ["typst", "typ"]
roots = []
comment-token = "//"
language-servers = ["typst-lsp"]
indent = { tab-width = 2, unit = "  " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'$' = '$'
'"' = '"'
