[[language]]
name = "html"
formatter = { command = 'npx', args = ["prettier", "--parser", "html"] }

[[language]]
name = "json"
config = { "json" = { "validate" = { "enable" = true } } }
formatter = { command = 'npx', args = ["prettier", "--parser", "json"] }

[[language]]
name = "css"
config = { "css" = { validate = { enable = true } } }
formatter = { command = 'npx', args = ["prettier", "--parser", "css"] }

[[language]]
name = "svelte"
auto-format = true
formatter = { command = 'npx', args = ["prettier", "--parser", "svelte"] }

[[language]]
name = "vue"
auto-format = true
formatter = { command = 'npx', args = ["prettier", "--parser", "vue"] }
