#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Program keybindings
riverctl map normal Super Return spawn alacritty
riverctl map normal Super O spawn firefox

# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+Shift+E to show power menu
riverctl map normal Super+Shift E spawn ~/.config/wofi/powermenu.sh

# Super+D to show wofi application menu
riverctl map normal Super D spawn ~/.config/wofi/launcher.sh

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Shift Left resize horizontal -100
riverctl map normal Super+Shift Top resize vertical 100
riverctl map normal Super+Shift Bottom resize vertical -100
riverctl map normal Super+Shift Right resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# control key mappings
for mode in normal locked
do
    # Control screen backlight brightness with light
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# Set style and cursor settings
riverctl background-color 0x242424
riverctl border-color-focused 0xffc0cb
riverctl border-color-unfocused 0x2e3440
riverctl xcursor-theme Qogir-dark 12

# Set keyboard repeat rate
riverctl set-repeat 30 200

# Make all views with an app-id that starts with "float" and title "foo" start floating.
riverctl rule-add float -app-id 'float*' -title 'foo'

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add csd -app-id "bar"

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
riverctl keyboard-layout de
rivertile -view-padding 6 -outer-padding 4 &
riverctl focus-follows-cursor normal

# Wallpaper
swaybg -i $(find ~/Projects/Artwork/Wallpaper/ | shuf -n 1) -m fill &

# Status bar
exec waybar &

# Audio
exec pipewire &
exec pipewire-pulse &

# Notifications
exec mako &

# Output configuration
exec kanshi &

# Input configuration
TOUCHPAD="$(riverctl list-inputs | grep Touchpad)"
riverctl input "$TOUCHPAD" events enabled
riverctl input "$TOUCHPAD" tap enabled
riverctl input "$TOUCHPAD" natural-scroll enabled
riverctl input "$TOUCHPAD" tap-button-map left-right-middle