#!/bin/bash

### Helper scripts for docker (compose)

prune() {
    sudo docker system prune -af --volumes
}

update() {
    sudo docker compose pull
    sudo docker compose up -d
}

case $1 in
p|prune) prune ;;
u|update) update ;;
esac
